version: '2'

services:
    web:
        image: nginx:1.15
        ports:
            - "8080:80"
        volumes:
            - /Users/weizeng/source/php:/code
            - /Users/weizeng/study/docker/nginx-env/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
        restart: always
    php:
        image: php:7.2-fpm
        volumes:
            - /Users/weizeng/source/php:/code
        networks:
            - code-network
        restart: always

networks:
    code-network:
        driver: bridge
